### PR TITLE
Add downloader for subset of files

### PR DESCRIPTION
**Pull request by 99991**
Thanks for the great dataset!

In fact, the dataset is so grand that it does not fit on my hard disk. Therefore, I made this download script which can download a specified subset of the images in the zip files.

For example, this command will download one image of each scene:

```bash
./dataset_download_images_partial.py --contains scene_cam_00_final_preview --contains frame.0000.color.jpg --silent
```

I hope that this script can be useful to other people who have limited hard drive space or bandwidth.

### CODE REVIEW

**Comment by mikeroberts3000** [comment]
Woah this is awesome! Thank you for putting this together. Instead of putting this file in `code/python/tools`, can you put it in `contrib/99991` with a top-level README file explaining how to use it?

**Comment by mikeroberts3000** [comment]
Also, I don't love this style of assembling the the URL string programmatically because it's harder for readers to understand what's going on. But otherwise I love this functionality.

**Comment by mikeroberts3000** [comment]
This is so awesome! 😀 Thank you. I'll make a note in the main README that you created this useful downloading tool 😀

**Comment by s1ddok** [comment]
@99991

I'm trying to use your script but for some reason it only traverses over `preview` folders and skips all `hdf5` files. Did you test it?

**Comment by mikeroberts3000** [comment]
Works for me on macOS and Windows.

```
(hypersim-env) Mikes-Mac-Pro-2013-Work:99991 mike$ python download.py --contains ai_001_001 --contains hdf5 --contains frame.0000 --silent
Downloading: downloads/ai_001_001/images/scene_cam_00_final_hdf5/frame.0000.color.hdf5
Downloading: downloads/ai_001_001/images/scene_cam_00_final_hdf5/frame.0000.diffuse_illumination.hdf5
Downloading: downloads/ai_001_001/images/scene_cam_00_final_hdf5/frame.0000.diffuse_reflectance.hdf5
Downloading: downloads/ai_001_001/images/scene_cam_00_final_hdf5/frame.0000.residual.hdf5
Downloading: downloads/ai_001_001/images/scene_cam_00_geometry_hdf5/frame.0000.depth_meters.hdf5
Downloading: downloads/ai_001_001/images/scene_cam_00_geometry_hdf5/frame.0000.normal_bump_cam.hdf5
Downloading: downloads/ai_001_001/images/scene_cam_00_geometry_hdf5/frame.0000.normal_bump_world.hdf5
Downloading: downloads/ai_001_001/images/scene_cam_00_geometry_hdf5/frame.0000.normal_cam.hdf5
Downloading: downloads/ai_001_001/images/scene_cam_00_geometry_hdf5/frame.0000.normal_world.hdf5
Downloading: downloads/ai_001_001/images/scene_cam_00_geometry_hdf5/frame.0000.position.hdf5
Downloading: downloads/ai_001_001/images/scene_cam_00_geometry_hdf5/frame.0000.render_entity_id.hdf5
Downloading: downloads/ai_001_001/images/scene_cam_00_geometry_hdf5/frame.0000.semantic.hdf5
Downloading: downloads/ai_001_001/images/scene_cam_00_geometry_hdf5/frame.0000.semantic_instance.hdf5
Downloading: downloads/ai_001_001/images/scene_cam_00_geometry_hdf5/frame.0000.tex_coord.hdf5
(hypersim-env) Mikes-Mac-Pro-2013-Work:99991 mike$
```

**Comment by s1ddok** [comment]
oh I realized that --contains has `and` semantics, I found it a bit more useful to have `or` semantics and updated to script to be able to use it like this (download only color and semantic images): 
```
python contrib/99991/download.py -d evermotion_dataset/scenes --contains .color.hdf5 --contains .semantic.hdf5
```

I only changed `all` to `any`
```
            contains_all_words = any(
                word in entry.filename for words in args.contains for word in words
            )
```

@99991 thanks for this script!!!

**Comment by mikeroberts3000** [comment]
Yay! And yes, thank you @99991. I didn't realize this functionality could be achieved in such a clean way, with so few lines of Python. Very cool 😀

**Pull request merged**
